import clsx from 'clsx'
import type { Metadata } from 'next'
import { MANROPE, ROBOTO_MONO } from '@/constants/fonts'
import DefaultLayout from '@/components/layouts/default-layout'
import '@/styles/index.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={clsx('scroll-smooth', MANROPE.variable, ROBOTO_MONO.variable)}>
      <body suppressHydrationWarning={true}>
        <DefaultLayout>
          {children}
        </DefaultLayout>
      </body>
    </html>
  )
}

interface Props {
  children: React.ReactNode
}
